### PR TITLE
feat: add unit tests for helm and kustomize templates

### PR DESCRIPTION
**Pull request by zreigz**

### CODE REVIEW

**Review by michaeljguarino — COMMENTED** [review]
What do these tests do functionally?  It doesn't seem like they're serving up a tarball but not entirely sure i'm reading it right

**Comment by zreigz** [comment]
> What do these tests do functionally? It doesn't seem like they're serving up a tarball but not entirely sure i'm reading it right

they read from a predefined test directory with different templates. They execute the 'Render' function to test templating

**Review by michaeljguarino — APPROVED** [review]

**Comment by zreigz** [comment]
@michaeljguarino please merge this PR because I am not authorized

**Comment by michaeljguarino** [comment]
I changed the settings to now allow merges w/o all gates passing so you can merge in the future @zreigz

**Pull request merged**
